# Generated by Django 5.0.1 on 2024-02-21 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AllFund',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(default='upload-image', upload_to='fundapp/images')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('required', models.DecimalField(decimal_places=10, max_digits=19)),
                ('have', models.DecimalField(decimal_places=10, max_digits=19)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_campaign', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
