# Generated by Django 5.0.2 on 2024-03-09 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usermessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AllFund',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(default='upload-image', upload_to='fundapp/images')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('campaignType', models.CharField(max_length=100)),
                ('required', models.DecimalField(decimal_places=10, max_digits=19)),
                ('have', models.DecimalField(decimal_places=10, default=0, max_digits=19)),
                ('slug', models.CharField(blank=True, max_length=130, unique=True)),
                ('timeStamp', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_campaign', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BankClaim',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('bankName', models.CharField(max_length=180)),
                ('accountNumber', models.CharField(max_length=150)),
                ('receivingName', models.CharField(max_length=100)),
                ('accountName', models.CharField(max_length=100)),
                ('receivingAddress', models.CharField(max_length=200)),
                ('phoneNumber', models.CharField(max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_claim_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EsewaClaim',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('phoneNumber', models.CharField(max_length=15)),
                ('receivingAddress', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='esewa_claim_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KhaltiClaim',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('phoneNumber', models.CharField(max_length=15)),
                ('receivingAddress', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='khalti_claim_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('medium', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=19)),
                ('amountReceiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_user_receiver', to=settings.AUTH_USER_MODEL)),
                ('campaignTitle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_campaign_title', to='fundapp.allfund')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_user_donator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
