# Generated by Django 5.0.2 on 2024-03-13 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='esewaclaim',
            name='receivedAmount',
            field=models.IntegerField(default=0),
        ),
    ]
