# Generated by Django 5.0.1 on 2024-03-13 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundapp', '0002_esewaclaim_receivedamount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esewaclaim',
            name='receivedAmount',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=19),
        ),
    ]
