# Generated by Django 5.0.1 on 2024-04-15 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundapp', '0003_alter_esewaclaim_receivedamount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='user',
        ),
        migrations.AddField(
            model_name='transaction',
            name='donator',
            field=models.CharField(default='Falano', max_length=100),
        ),
    ]
